# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

anova_cuda <- function(vX, vN, vsigma, mu, vtau, vpair, B, alpha, method, R, nblock, threads_per_block, seed) {
    .Call('_hdanova_cuda_anova_cuda', PACKAGE = 'hdanova.cuda', vX, vN, vsigma, mu, vtau, vpair, B, alpha, method, R, nblock, threads_per_block, seed)
}

